url: http://jemonjam.com
title: jemonjam
description: 'Builder of things, muser of musings'
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title
plugins:
    - jekyll-sitemap
    - jekyll-feed

defaults:
    - scope:
          path: "lab/classpass-marketing-test"
      values:
          layout: "classpass-page"
